CREATE TABLE Books (
bookId INT NOT NULL IDENTITY (1, 1) PRIMARY KEY,
bookName VARCHAR (200) NOT NULL,
isbn VARCHAR (20) NOT NULL,
autor VARCHAR (100) NOT NULL,
);

CREATE TABLE Categories (
catId INT NOT NULL IDENTITY (1, 1) PRIMARY KEY,
catName VARCHAR (100) NOT NULL,
createDate DATE NOT NULL DEFAULT GETDATE(),
);

CREATE TABLE BooksCategories (
bookId INT NOT NULL REFERENCES Books (bookId),
catId INT NOT NULL REFERENCES Categories (catId),
);

ALTER TABLE BooksCategories
ADD CONSTRAINT BooksCategoriesPK PRIMARY KEY (bookId, catId);